learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='basic_app'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r"^$",views.index,name='index'),
    path('admin/', admin.site.urls),
        url('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r"^logout/$",views.user_logout,name='logout'),
    url(r"^special/$",views.special,name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,)

    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    age=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password','age')


class  UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse('you are loggedin   ')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered=False
    if request.method =='POST' :
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid() :

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user


            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active!!")

        else:
            print('some one tried to login and failedd ')
            print('Username : {} and password {} '.format(username,password))
            return HttpResponse('invalid login details !!')
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
 <!DOCTYPE html>
 {% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

  </head>
  <body>
    <div class="container">
<div class="jumbotron">


        <h1>Information of the page!!</h1>
</div>
      </div>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">

        <ul class="nav">
  <li class="nav-item">
    <a class="nav-link brand" href="{% url 'index' %}">HOME</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'basic_app:register' %}">REGISTER</a>
  </li>
  {% if user.is_authenticated  %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
  </li>
  {% endif %}


</ul>

  </div>
    </nav>

    {% block body_block %}
       <div class="container">

       </div>
    {% endblock %}

  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
  {% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="container">
<div class="jumbotron">


    <h1>WELCOME TO the CALORIES CALC.</h1>
    <a class="btn btn-primary" href="https://www.freedieting.com/calorie-calculator" role="button">CalorieCal</a>


</div>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
  {% extends 'basic_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form class="" action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <input type="text" name="username" placeholder="enter username">
<label for="password">Password</label>
<input type="password" name="password" >
  <input type="submit" name="" value="LOGIN">

    </form>

</div>


{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
  {% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="container">


  <div class="jumbotron">
   {% if registered  %}

   <h1>Thankyou for the registaration!!!</h1>


    <a class="btn btn-primary" href="{% static 'pic.png' %}" role="button">CaloriePage</a>
      <a class="btn btn-primary" href="https://www.freedieting.com/calorie-calculator" role="button">CalorieCal</a>
{% else %}
   <h1>Register Here !!</h1>
   <h3>Fill out the form !!</h3>

   <form method="post" enctype="multipart/form-data">

     {% csrf_token %}
     {{ user_form.as_p }}
     {{ profile_form.as_p }}
     <input type="submit" name="" value="Register">
   </form>

   {% endif %}

  </div>
  </div>

{% endblock %}